name: base
channels:
  - conda-forge
dependencies:
  # runtime dependencies
  - python >=3.10,<3.12
  - nodejs >=16,<17
  - yarn

  # Dependencies
  - jupyterlab >=4.5.1

  # Binder
  - jupyterlab-link-share=0.2
