name: Build

on:
  push:
    branches: main
  pull_request:
    branches: '*'

jobs:
  build:
    name: Build jupytergis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.12']

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: gis
          create-args: >-
            python=${{ matrix.python-version }}
            jupyterlab=4
            yarn=3
            pillow
            mercantile
            xyzservices

      - name: Setup pip cache
        uses: actions/cache@v5
        with:
          path: ~/.cache/pip
          key: pip-${{ matrix.python-version }}-${{ hashFiles('package.json') }}
          restore-keys: |
            pip-${{ matrix.python-version }}-
            pip-

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Setup yarn cache
        uses: actions/cache@v5
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-

      - name: Build the extension
        shell: bash -l {0}
        run: |
          set -eux
          yarn install
          yarn dev
          jupyter labextension list 2>&1 | grep -ie "jupytergis-core.*OK"
          jupyter labextension list 2>&1 | grep -ie "jupytergis-lab.*OK"

      - name: Package the extension
        shell: bash -l {0}
        run: |
          set -eux
          pip install build
          yarn build:packages

      - name: Upload extension packages
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.python-version == '3.12' && 'extension-artifacts' || format('extension-artifacts-{0}', matrix.python-version) }}
          path: |
            python/jupytergis/dist/jupytergis*
            python/jupytergis_core/dist/jupytergis*
            python/jupytergis_lab/dist/jupytergis*
            python/jupytergis_qgis/dist/jupytergis*
            python/jupytergis_lite/dist/jupytergis*
          if-no-files-found: error

  validate-examples:
    name: Validate example .jGIS files
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: gis
          create-args: >-
            python=3.12
            yarn=3

      - name: Install dependencies
        shell: bash -l {0}
        run: yarn install

      - name: Validate example .jGIS files against schema
        shell: bash -l {0}
        run: node packages/schema/scripts/validate-examples.js

  python_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.12']

    steps:
      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: gis
          create-args: >-
            python=${{ matrix.python-version }}
            jupyterlab=4
            yarn=3
            qgis

      - name: Checkout
        uses: actions/checkout@v6

      - name: Install
        shell: bash -l {0}
        run: python scripts/dev-install.py

      - name: Install test packages
        shell: bash -l {0}
        run: pip install pytest dirty-equals

      - name: Run tests
        shell: bash -l {0}
        run: pytest --color=yes -v python/jupytergis_qgis/jupytergis_qgis/tests

      - name: Run Python API tests
        shell: bash -l {0}
        run: pytest --color=yes -v python/jupytergis_lab/

  fresh_yarn_lock_test:
    runs-on: ubuntu-latest

    steps:
      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: gis
          create-args: >-
            pip
            jupyterlab=4
            yarn=3

      - name: Checkout
        uses: actions/checkout@v6

      - name: Install build deps
        shell: bash -l {0}
        run: pip install -r requirements-build.txt

      - name: Build with a fresh yarn
        shell: bash -l {0}
        run: |
          rm yarn.lock
          jlpm
          jlpm run build:prod

  test_isolated:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v7
        with:
          name: extension-artifacts

      - name: Install and Test
        shell: bash -l {0}
        run: |
          set -eux
          # Remove NodeJS, twice to take care of system and locally installed node versions.
          sudo rm -rf $(which node)
          sudo rm -rf $(which node)

          cp ./jupytergis/dist/jupytergis*.whl ./jupytergis_core/dist/jupytergis*.whl ./jupytergis_lab/dist/jupytergis*.whl ./jupytergis_qgis/dist/jupytergis*.whl .
          python -m pip install jupytergis*.whl "jupyterlab==4.5.1"

          jupyter labextension list
          jupyter labextension list 2>&1 | grep -ie "jupytergis.*OK"

  integration-tests:
    name: Integration tests
    needs: build
    runs-on: ubuntu-latest

    env:
      PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/pw-browsers

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          micromamba-version: '1.5.5-0'
          environment-name: gis
          create-args: >-
            python=3.12
            jupyterlab
            ipywidgets
            qgis

      - name: Download extension package
        uses: actions/download-artifact@v7
        with:
          name: extension-artifacts

      - name: Install the extension
        shell: bash -l {0}
        run: |
          set -eux
          cp ./jupytergis/dist/jupytergis*.whl ./jupytergis_core/dist/jupytergis*.whl ./jupytergis_lab/dist/jupytergis*.whl ./jupytergis_qgis/dist/jupytergis*.whl .
          python -m pip install jupytergis*.whl "jupyter-collaboration>=4,<5" "jupyterlab==4.5.1"

      - name: Install
        shell: bash -l {0}
        working-directory: ui-tests
        run: |
          jlpm install
          yarn playwright install chromium

      - name: Execute integration tests
        shell: bash -l {0}
        working-directory: ui-tests
        run: jlpm run test

      - name: Upload Playwright Test report
        id: upload-galata-artifact
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: jupytergis-playwright-tests
          path: |
            ui-tests/test-results
            ui-tests/playwright-report

      - name: Save artifact data
        if: always()
        uses: trungleduc/appsharingspace-pr-comment/.github/actions/save-artifact-link@v2
        with:
          output_name: galata-apss
          artifact_link: 'https://github.com/${{ github.repository }}/actions/runs/${{github.run_id}}/artifacts/${{ steps.upload-galata-artifact.outputs.artifact-id }}'

  check_linting:
    name: Lint check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: gis
          create-args: >-
            python=3.12
            jupyterlab=4
            yarn=3

      - name: Lint
        shell: bash -l {0}
        run: |
          jlpm install
          jlpm run eslint:check
          jlpm run prettier:check

  check_links:
    name: Check Links
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - uses: jupyterlab/maintainer-tools/.github/actions/check-links@v1
        with:
          ignore_links: >-
            lite/
            https://www\.npmjs\.com.*
            ^/.*
            https://blog\.jupyter\.org/.*
            https://medium\.com/.*

  build-lite:
    name: Build JupyterLite artifacts
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          micromamba-version: '1.5.5-0'
          environment-name: build-env
          create-args: >-
            python=3.10
            pip
            jupyterlite-core
            jupyterlite-xeus
            jupyter_server
            specta

      - name: Download extension package
        uses: actions/download-artifact@v7
        with:
          name: extension-artifacts

      - name: debug
        run: ls

      - name: Install the extension
        shell: bash -l {0}
        run: |
          set -eux
          cp ./jupytergis_core/dist/jupytergis*.whl jupytergis_core-0.0.1-py3-none-any.whl
          cp ./jupytergis_lab/dist/jupytergis*.whl jupytergis_lab-0.0.1-py3-none-any.whl
          cp ./jupytergis_qgis/dist/jupytergis*.whl jupytergis_qgis-0.0.1-py3-none-any.whl
          cp ./jupytergis_lite/dist/jupytergis*.whl jupytergis_lite-0.0.1-py3-none-any.whl
          cp ./jupytergis/dist/jupytergis*.whl jupytergis-0.0.1-py3-none-any.whl

      - name: Build JupyterLite
        shell: bash -l {0}
        working-directory: lite
        run: |
          set -eux
          cp --recursive --dereference ../ui-tests/content ./content
          find ./content -type d -name ".ipynb_checkpoints" -exec rm -rf {} +
          jupyter lite build --contents content --output-dir dist

      - name: Upload Lite artifacts
        uses: actions/upload-artifact@v6
        with:
          name: lite-artifacts
          path: ./lite/dist
          retention-days: 30

  integration-tests-lite:
    name: Integration tests Lite
    needs: build-lite
    runs-on: ubuntu-latest

    env:
      PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/pw-browsers

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          micromamba-version: '1.5.5-0'
          environment-name: gis
          create-args: >-
            python=3.9
            jupyterlab

      - name: Download extension package
        uses: actions/download-artifact@v7
        with:
          name: lite-artifacts
          path: dist

      - name: Install dependencies
        shell: bash -l {0}
        working-directory: ui-tests
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: jlpm install

      - name: Set up browser cache
        uses: actions/cache@v5
        with:
          path: |
            ${{ github.workspace }}/pw-browsers
          key: ${{ runner.os }}-${{ hashFiles('ui-tests/yarn.lock') }}

      - name: Install browser
        shell: bash -l {0}
        run: npx playwright install chromium
        working-directory: ui-tests

      - name: Execute integration tests
        shell: bash -l {0}
        working-directory: ui-tests
        run: jlpm run test:lite

      - name: Upload Playwright Test report
        id: upload-galata-artifact
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: jupytergis-lite-playwright-tests
          path: |
            ui-tests/test-results
            ui-tests/playwright-report
