# The ReadTheDocs preview link is "hidden" within the GitHub "Checks"
# interface. For users who don't know this, finding the preview link may be
# very difficult or frustrating. This workflow makes the link more
# findable by updating PR descriptions to include it.
name: 'Add ReadTheDocs preview link to PR description'

on:
  pull_request_target:
    types:
      - 'opened'

permissions:
  pull-requests: 'write'

jobs:
  autolink-rtd-previews:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'mfisher87/readthedocs-actions/preview@main'
        with:
          project-slug: 'jupytergis'
          message-template: |
            ---
            ðŸ“š Documentation preview: {docs-pr-index-url}
            ðŸ’¡ JupyterLite preview is available from the doc, by clicking on [![lite badge](https://jupyterlite.rtfd.io/en/latest/_static/badge.svg)]({docs-pr-index-url}/lite)
