name: Update Galata References

on:
  issue_comment:
    types: [created, edited]

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: bash -l {0}

jobs:
  update-snapshots:
    runs-on: ubuntu-latest

    # Only run on issue comments
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'please update snapshots')

    steps:
      - uses: jupyterlab/maintainer-tools/.github/actions/update-snapshots-checkout@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download extension package
        uses: dawidd6/action-download-artifact@v14
        with:
          pr: ${{github.event.issue.number}}
          workflow: 'build.yml'
          workflow_conclusion: ''
          name: extension-artifacts
          allow_forks: true

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: gis
          create-args: >-
            python=3.10
            jupyterlab=4
            jupyter-collaboration

      - name: Install the extension
        shell: bash -l {0}
        run: |
          whereis python
          cp ./jupytergis_core/dist/jupytergis*.whl ./jupytergis_lab/dist/jupytergis*.whl ./jupytergis_qgis/dist/jupytergis*.whl ./jupytergis/dist/jupytergis*.whl .
          python -m pip install jupytergis*.whl

      - name: Install dependencies
        shell: bash -l {0}
        working-directory: ui-tests
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: |
          jlpm install
          yarn playwright install

      - uses: jupyterlab/maintainer-tools/.github/actions/update-snapshots@main
        with:
          npm_client: jlpm
          browser: chromium
          github_token: ${{ secrets.GITHUB_TOKEN }}
          start_server_script: 'null'
          test_folder: ui-tests
