name: Update Lite Galata References

on:
  issue_comment:
    types: [created, edited]

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: bash -l {0}

jobs:
  update-lite-snapshots:
    runs-on: ubuntu-latest

    # Only run on issue comments
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'please update snapshots')

    steps:
      - uses: martinRenou/maintainer-tools/.github/actions/update-snapshots-checkout@check_perm
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download extension package
        uses: dawidd6/action-download-artifact@v12
        with:
          pr: ${{github.event.issue.number}}
          workflow: 'build.yml'
          workflow_conclusion: ''
          name: lite-artifacts
          path: dist
          allow_forks: true

      - name: Install dependencies
        shell: bash -l {0}
        working-directory: ui-tests
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: |
            pip install jupyterlab
            jlpm install
            yarn playwright install

      - uses: jupyterlab/maintainer-tools/.github/actions/update-snapshots@main
        with:
          npm_client: jlpm
          browser: chromium
          github_token: ${{ secrets.GITHUB_TOKEN }}
          start_server_script: 'null'
          test_folder: ui-tests
          update_script: test:updatelite
